M7R0
I)GIAIHANG=6"%&falseGE\[l%%3FindRankUsingGaussGt+6#'%/mtLinearMatrixGI'MatrixG6
$%*protectedG%(_syslibG64%)mtResultG%*lSolutionG%0lMatrixSolutionG%$cotG%%dongG
%"iG%"jG%%hesoG%/numColStandardG%2iPosStartStandardG%&firstG%*lSoluTempG%)iPosS
oluG%,mtResultPreG%.mtResultAfterG%,iPosReplaceG%'resultG%%rootGF$F$C2-I'printf
G6$F.F/6#%bo~\\~~\\~--|[x|hza_Ma_Tr&#7853;n_v&#7873;_Ma_Tr&#7853;n_b&#7853;c_th
ang--~\\G-FE6#%M~\\~~\\~Ma_Tr&#7853;n_nh&#7853;p_v|[yo_l|[y_:~\\G-I&latexG6$F.F
/6#9$>8%7">8&FS>8$-F,FO>8'-_I.LinearAlgebraG6$F.F/%0ColumnDimensionGFO>8(-_Fgn%
-RowDimensionGFO>8,""!>8.Fao>8-""">8/FS>80Ffo?(8)FfoFfoFZ%%trueG@%1FeoF[oC$>81-
F,6#FW@%0&FW6$FeoF\pFaoC)?(8*,&FeoFfoFfoFfoFfoF[oF]pC$>8+-%/FindCofficientG6$Fg
p&FW6$F[qF\p@$0F_qFaoC%-_Fgn%-RowOperationG6&FW7$F[qFeoF_q/%(inplaceGF]p>Fho7&F
\pFjoF\rF_q>FR7$-%#opG6#FRFho>FeoF\q>F`o,&F`oFfoFfoFfo>82Fcp@$/-_Fgn%&EqualG6$F
WFbpF%C$>FU7$-Fdr6#FUFjr>Fjo,&FjoFfoFfoFfo-FE6#%)~\\~<=>_G-FM6#FjrC$>83-%0Posit
ionReplaceG6&FWFeoF\pF[o@$0F_tFaoC,-Fiq6%FW7$FeoF_tF]r>Fho7%F\pFjoFht>FRFbr?(F[
qF\qFfoF[oF]pC$>F_qF`q@$FfqC%Fhq>FhoF`r>FRFbr>FeoF\q>F`oFhr>FjrFcp@$F\sC$>FUFcs
>FjoFgsFhsF[t[-%&printG6#%V\\~V&#7853;y_h&#7841;ng_c&#7911;a_ma_tr&#7853;n_l|[y
_:_G-F\v6#F`oF$F$F$6#FfoFaqt+6$%"aG%"bG6#FAF$F$C%@$/9%FaoOFao>FW,$-I)simplifyG6
$F.F/6#*&FjvFfoFP!""FcwOFWF$F$F$6#""#%%initGt+F$F$F$F$F$F$6$%%exprG%"xGF$6#FaoF
att+6&%)mtMatrixG%*vitridongG%)vitricotGF56$F6F7F$F$C$?(FW,&FjvFfoFfoFfoFfo9'F]
p@$0&FP6$FW9&FaoOFWOFaoF$F$F$6#""%F$
