M7R0
I)GIAIDSTT=6"%&falseGE\[lB%3FindEleDistanceMinGt+6&%)mtResultG%2iPosStartStanda
rdG%)vitricotG%%dongG6(%"iG%%lDisG%#kcG%%iMinG%$posG%%tempGF$F$C)>8)7">8%F8?(8$
,&9%"""F?F?F?9'%%trueG@$0&9$6$F<9&""!C%>8&-%$absG6#,&-FM6#&FE6$F>FGF?-FM6#FD!""
>F77$F<FK>F:7$-%#opG6#F:F7>8'&&F:6#F?6#""#>8(&F[oF\o?(F<F^oF?-%%nopsGFgnFA@$2&&
F:6#F<F]oFinC$>FinFgo>F`o&FhoF\oOF`oF$F$F$6#""%%/CheckNumberOneGt+F)6#F/F$F$C$?
(F<F=F?F@FA@$5/FDF?/FDFVOF<OFHF$F$F$6#F`p%1FindPositionParaGt+6'%)mtMatrixG%*vi
tridongGF,%%nrowG%%ncolG6%F/%&ldongG%&vitriGF$F$C%>F:F8?(F<F=F?F@FA@$/-%*CheckP
araGFUF?>F:7$FenF<@'/FcoFHOFH/FcoF?OF[oC$>FK-%6FindRowPriorityToZeroG6&FEF:FG9(
OFKF$F$F$6#""&%4PositionReplaceZeroGt+F_q6&F/FeqFfq%&checkGF$F$C%>Fin-%4Positio
nReplaceParaG6'FEF>FGF@Fjr@%0FinFHOFinC$>Fin-F]qFfs@$FhsOFinOFHF$F$F$6#F]s%1uit
MatrixInverseGt+6$'%"aG%'MatrixG%#~$G6#%'resultGF$F$C$@%/9#FHYQepinvalid~input:
~uitMatrixInverse~uses~a~1st~argument,~a~(of~type~Matrix),~which~is~missing~F$@
%4-%%typeG6$&9"F\oFftYQ\pinvalid~input:~uitMatrixInverse~expects~its~1st~argume
nt,~a,~to~be~of~type~MatrixF$>F<-%1uitCramerInverseG6#FEOF<F$F$F$6#F^oFest+F_qF
dqF$F$C%>F:F8?(F<F=F?F@FA@$3FC/F\rFH>F:F_r@'FarOFHFcrOF[oC$>FK-%6FindRowPriorit
yToParaGFirOFKF$F$F$6#F]s%,MatrixStairGt+6#'%/mtLinearMatrixGFft6=F*%*lSolution
G%0lMatrixSolutionG%$cotGF-F/%"jG%"kG%%hesoG%/hesochuarutgonG%/numColStandardGF
+%&firstG%*lSoluTempG%)iPosSoluG%,mtResultPreG%.mtResultAfterG%,iPosReplaceG%(c
heckVNGFit%#VNG%%rootG%*finalrootG%.checktoanzeroG%)tinhtoanG%%rankG%%ruleGF$F$
C3>8>FA-%&printG6#Q\o~\\~===~Bi&#7871;n_|[z&#7893;i_Ma_tr&#7853;n_b&#7853;c_tha
ng~===\\~F$-F`y6#QU~\\~Ta_c|^z_Ma_tr&#7853;n_m&#7903;_r&#7897;ng_sau.~\\~F$-%&l
atexGF\v>F:F8>FKF8>F<-FftF\v>Fin-_I.LinearAlgebraG6$%*protectedG%(_syslibG%0Col
umnDimensionGF\v>F`o-_F_z%-RowDimensionGF\v>8.FH>80FH>8/F?>81F8>82F?>88F%>86-%0
CheckNoSolutionG6%F<F`oFin@%0Fe[lFH>Fc[lFAC&?(F7F?F?,&FinF?FVF?FA@%1F][lF`oC&>8
3-FftFio@%0&F<6$F][lF7FHC(?(8*,&F][lF?F?F?F?F`oFAC%>8,-%/FindCofficientG6$Fg\l&
F<6$F[]lF7>8--%:FindCofficientNotSimplifyGFb]l@$0F_]lFHC%-_F_z%-RowOperationG6&
F<7$F[]lF][lFf]l/%(inplaceGFA>F_[l7&F7Fa[lF`^lF_]l>F:7$FenF_[l?(8+F?F?,&F`oF?FV
F?FA@$-_F_z%&EqualG6$-_F_z%$RowG6$F<Fh^l-&%'VectorG6#%$rowG6#FinC$>8;-%4CheckRo
wHaveAllZeroG6&F<Fh^lF`oFin@$0F[`lFHC%-F]^l6%F<7$Fh^lF[`lFa^l>F_[l7%F7Fa[lFd`l>
F:Ff^l>F][lF\]l>Fiz,&FizF?F?F?>84Fd\l@$/-F\_l6$F<Fc\lF%C$>FK7$-Ffn6#FKF\al>Fa[l
,&Fa[lF?F?F?C$>85-%0PositionReplaceG6&F<F][lF7F`o@$0FjalFHC+-F]^l6%F<7$F][lFjal
Fa^l>F_[l7%F7Fa[lFcbl>F:Ff^l?(F[]lF\]lF?F`oFAC%>F_]lF`]l>Ff]lFg]l@$Fj]lC%F\^l>F
_[lFd^l>F:Ff^l?(Fh^lF?F?Fi^lFA@$F[_lC$>F[`lF\`l@$F``lC%Fb`l>F_[lFf`l>F:Ff^l>F][
lF\]l>F\alFd\l>FizFj`l@$F^alC$>FKFcal>Fa[lFgal>Fe[lFf[l@$Fj[lC%>876&FHFHF:FK>Fc
[lFA[Fedl?(Fh^lF?F?-FdoFealFAC%?(F[]lF?F?FcoFAC$>8<&F:6#F[]l@$/&F\elF\oFh^l-%'p
rintfG6'Q6~\\~D%d=%dD%d+D%d~\\~F$&&F\el6#""$F\o&F\el6#F`p&F\elF]oFfel-Fcel6#Q$=
=>F$-Fgy6#&FK6#Fh^l>8=-%4FindRankStairMatrixG6#&FK6#Fgdl-F`y6$%O~\\~~H&#7841;ng
_c&#7911;a_Ma_tr&#7853;n_l|[y_:_~GFeflF$F$F$6#F?%6uitLinearSolveNotParaGt+6&Fet
Fgt>'%'methodG%'symbolG%"GG>'F[yFegl%&FalseG6&Fit%%hypoGFdw%%lVarGF$F$C&@$45-Fc
u6$Feu%%listGFbuYQbqinvalid~input:~uitLinearSolve~expects~its~1st~argument,~a,~
to~be~of~type~Matrix~or~list,~but~received~aF$@%4-Fcu6$FEFftC%>F:-%1InitLinearM
atrixGF\v>FKF[o>Fin&F:F]o>FKFE@%F\uYQcpinvalid~input:~uitLinearSolve~uses~a~1st
~argument,~a~(of~type~Matrix),~which~is~missing~F$C$@$30F@%%TrueG0F@FiglYQinInv
alid~Syntax:~rule~must~have~syntax:~rule=True~or~rule=FalseF$@'/FGFfgl>F<-%,Met
hodGaussG6$FKF@/FG%#InGC$@$FgilYF\jl@%/F@Figl>F<-%6uitLinearSolveInverseG6$FK/-
%(convertG6$Q%ruleF$FeglFigl>F<-F\[m6$FK/F_[mFiilYQ/Invalid~SyntaxF$OF<F$F$F$6#
F^oFg[lt+6%F`qF-Fhw6&F/FiwF3FasF$F$C$?(F<F?F?F>FAC%>FinFA?(F:F?F?,&FGF?FVF?FA@$
0&FE6$F<F:FHC$>FinF%Fedl@$/FinFAC$>FKF<Fedl@%F[]m@%0&FE6$FKFGFHOFKOFHOFHF$F$F$6
#FielF\blt+6&F`qFaqF,F-6$F/FiwF$F$C$?(F<F=F?F@FA@$FCOF<OFHF$F$F$6#F`pF]ilt+6#'%
(lSystemGFchl6#F\hlF$F$Z%C$>F<7#-Ffn6#-%(SetVarsGF\vO6$-_F_z%/GenerateMatrixG6%
FEF</%*augmentedGFAF<F$OQ+InputErrorF$F$F$F$6#F?%7CreateMatrixNoVariableGt+6$'%
"AGFft'%(setvariG%$setG6%F/%"nGFetF$F$C&>FKF[z>F:-Fdo6#F>?&F<F>FA>FK-%%subsG6$/
F<F?FKOFKF$F$F$6#F^o%4CheckDivisorAndZeroGt+6'F*F+F,F-%'columnG6%F/%'check0G%-c
heckdivisorGF$F$C)>F:FA>FKFA@$/FRFVOF??(F<F=F?F@FA@$FC>F:F%?(F<,&FGF?F?F?F?FjrF
A@$3-Fcu6$&FE6$F>F<%(integerG-Fcu6$FRFgbm@$0-%%iremG6$FebmFRFH>FKF%@$5/F:FA/FKF
AOF?OFHF$F$F$6#F]sF[vt+Fbw61%$DetG%,lValueMinorGFg_lFbamF/FiwF*%'lRulesGF\`mFit
%0fValueParameterG%"DG%)CongthucG%(amatrixG%+listmatrixGF$F$C@>FKF]z>FinFez>F:F
8@$0FKFinYQCMatrix~input~must~is~square~matrixF$>F<-_F_z%,DeterminantGF\v>Fiz-%
&solveG6#/F<FH@$FaemOFH>Fh^l7#/F_]lFE>Fa[lF8?(F`oF?F?FKFAC%>F_[lF8?(F7F?F?FKFAC
%@%/)FV,&F`oF?F7F?F?>Fh^l7$-FfnFcfl/&F][l6$F`oF7-_F_z%&MinorG6&FEF`oF7/%'output
G.%'matrixG>Fh^l7$Fcfm/Fefm--F`[m6$F_fmFegl6#Fgfm>F_[l7$-Ffn6#F_[lFefm>F:7$Fen*
&-Fhfm6%FEF`oF7F?F_fmF?>Fa[l7$-Ffn6#Fa[lF_[l>F[[l-Fft6%FKFKFa[l>F[]l*&-_F_z%*Tr
ansposeG6#-Fft6%FKFKF:F?F<FV?(F`oF?F?FKFA?(F7F?F?FKFA>&F[]l6$;F`oF`o;F7F7-Fft6#
7#-%'normalG6#&&F[]l6#F`o6#F7@%0-Fdo6#-F\_mFioFH>Ff]l6(F?F[]lFh^l7$F<Fen7$Fhhm*
$F<FV7#Fiz>Ff]l6'F?F[]lFh^lFfjmFgjm-F`y6#%P\\~Gi&#7843;i_b&#7857;ng_ph|hz|`zng_
ph|\yp_Cramer.~\\G-Fgy6#&Fh^lF\o-F`y6#%<\\~Ta_c|^z_c|_zng_th&#7913;c___G-Fgy6#/
*$F_]lFV*$-FM6#F_]lFV-F`y6#%#\\G-Fgy6#F[[l-Fcel6$Q.\\~|grA|gr=%a~\\~F$F<?(F`oF^
oF?-FdoFcflFAC&-Fgy6#&Fh^lF]jm-F`y6#%$_=_G-Fgy6#&F:6#Fi^lF\\n-F`y6#%V\\~Ta_c|^z
_Ma_tr&#7853;n_ngh&#7883;ch_|[z&#7843;o_sau_:\\G-Fgy6#Fh[nFj\n-Fgy6#Fhjm-F`y6#%
".G-Fgy6#FhhmFj\n-FgyF^elF$F$F$6#F?Fajlt+Fbw6<F*FfwFgwFhwF-F/FiwFjwF[xF\xF]xF+F
^xF_xF`xFaxFbxFcxFdxFitFexFfxFgxFhxFixF[yF$F$C5>FeflFAF_yFcyFfy>F:F8>FKF8>F<F[z
>FinF]z>F`oFez>FizFH>F[[lFH>F][lF?>F_[lF8>Fa[lF?>Fc[lF%>Fe[lFf[l@%Fj[l>Fc[lFAC$
?(F7F?F?F^\lFA@%F`\lC&>Fc\lFd\l@%Ff\lC(?(F[]lF\]lF?F`oFAC%>F_]lF`]l>Ff]lFg]l@$F
j]lC%F\^l>F_[lFd^l>F:Ff^l?(Fh^lF?F?Fi^lFA@$F[_lC$>F[`lF\`l@$F``lC%Fb`l>F_[lFf`l
>F:Ff^l>F][lF\]l>FizFj`l>F\alFd\l@$F^alC$>FKFcal>Fa[lFgalC$>FjalF[bl@$F_blC+Fab
l>F_[lFebl>F:Ff^l?(F[]lF\]lF?F`oFAC%>F_]lF`]l>Ff]lFg]l@$Fj]lC%F\^l>F_[lFd^l>F:F
f^l?(Fh^lF?F?Fi^lFA@$F[_lC$>F[`lF\`l@$F``lC%Fb`l>F_[lFf`l>F:Ff^l>F][lF\]l>F\alF
d\l>FizFj`l@$F^alC$>FKFcal>Fa[lFgal>Fe[lFf[l@$Fj[lC%>FbdlFcdl>Fc[lFAFedlFedl?(F
h^lF?F?FgdlFAC%?(F[]lF?F?FcoFAC$>F\elF]el@$F`elFbelF]flF`fl@$4Fc[lC$@%/FKF8C$-F
cel6#Q\o\\~Ma_tr&#7853;n_|[z|hza_v|[yo_kh|_zng_c&#7847;n_bi&#7871;n_|[z&#7893;i
.~\\F$>89-_F_z%,LinearSolveG6$FE/Fdgl%#LUG>Fadn-Fcdn6$FiflFfdn@%2FizF^\lC'>8:-%
,ConvertRootG6#Fadn-F`y6#%co\\~H&#7879;_ph|hz|`zng_tr&igrave;nh_|[z&atilde;_c|^
z_d&#7841;ng_b&#7853;c_thang.G-F`y6#%gn\\~H&#7879;_ph|hz|`zng_tr&igrave;nh_c|^z
_v|_z_s&#7889;_nghi&#7879;m.G-F`y6#%^o\\~Ta_c|^z_nghi&#7879;m_t&#7893;ng_qu|\yt
_h&#7879;_ph|hz|`zng_tr&igrave;nh.G-Fgy6#F_enC$-F`y6#%P~\\~Ta_c|^z_k&#7871;t_qu
&#7843;_nghi&#7879;m~:\\~G?(F7F?F?,&-FdoFbenF?F?F?FAC%-Fcel6$Q,\\~x[%d]~=~F$F7-
Fgy6#&FadnF^jm-F`y6#%%~\\~G@$/&FbdlF\oFH-F`y6#%R~\\~H&#7879;_ph|hz|`zng_tr&igra
ve;nh_v|_z_nghi&#7879;m.GF$F$F$6#F?%7FindCofficientElement1Gt+6$Fet%"bGFhtF$F$C
$>F<*&,&F?F?FEFVF?F>FVOF<F$F$F$6#F^oFa]lt+FhgnFhtF$F$C%@$/F>FHOFH>F<,$-%)simpli
fyG6#*&F>F?FEFVFVOF<F$F$F$6#F^oF]wt+6&F[`m'%%lrowGFchlF,Fcq6*F/Fiw%'lvitriG%&lt
empG%"rG%$demG%(lonnhatGF3F$F$C(>FKF8?&F<F>FAC(>FinF8>F`o-F`_l6$FEF<>F7FH?(F:FG
F?F@FA@%/-F]r6#&F`oFgnFH>F7,&F7F?F?F?Fedl>Fin7$F<F7>FK7$FdalFin>F[]l&&FKF\oF]o>
Fh^l&F^[oF\o?(F<F^oF?FgdlFA@$2F[]l&&FKFioF]oC$>F[]lFd[o>Fh^l&Fe[oF\oOFh^lF$F$F$
6#F`pFgflt+6#F[`m6(F/FbqFcq%&rzeroGFg_lFjxF$F$C(>F:Fez>FKF]z>Fin-&Fe_lF]jm6$FK/
%&shapeG%%zeroG>F7FH?(F<F?F?F:FAC$>F`oF]jn@$4-F\_l6$F`oFin>F7FgjnOF7F$F$F$6#F?F
]`lt+6&'%"mGFft%-dongToanZeroG%&idongG%%icotGFcpF$F$C$?(F<F=F?FGFA@$4-F\_l6$F]j
n-Fd_l6#F@OF<OFHF$F$F$6#F`pFh]lt+FhgnFhtF$F$C%@$FchnOFH>F<,$FjhnFVOF<F$F$F$6#F^
oF]rt+6#FetF$F$F$C$@$55-Fcu6$FEFgbm-Fcu6$FE%)fractionG-Fcu6$FE%&floatGOFHOF?F$F
$F$6#F?%%initGt+F$F$F$F$F$F$F$F$6#FH%(GetParaGt+6#'%'largueGFchl6#%%paraGF$F$C$
>F<-%$rhsG6#&FEF\oOF<F$F$F$6#F?%3uitLinearSolveParaGt+6'F[`mFi`oFgt>FcglFfgl>Fh
glFigl6$FitFetF$F$C%>F:F[z@$FauYQ^qinvalid~input:~uitLinearSolvePara~expects~it
s~1st~argument,~a,~to~be~of~type~Matrix,~but~received~AF$@%5F\u/F]uF?YQ[rinvali
d~input:~uitLinearSolvePara~needs~2~parameter,~1st~argument~has~type~Matrix,~2n
d~argument~has~type~symbol~F$C%@$30FjrFiil0FjrFiglYF\jl@%/F@Ffgl>F<-%/uitLinear
ArgueG6%F:F>FjrYQ<Invalid~syntax:~method~=~G~F$OF<F$F$F$6#Fiel%4FactorElementMa
trixGt+6%F[`mFbqFcq6&F/FiwFet%)mtFactorGF$F$C&>FKF[z>FinF[z?(F<F?F?F>FA?(F:F?F?
FGFA>&FinFg\m-%'factorG6#&FKFg\mOFinF$F$F$6#FielF\cot+6%F[`mFi`oFdin67F/FiwFetF
bqFcq%,rOpenMatrixG%/rNotOpenMatrixG%'mtOpenG%*mtNotOpenG%(mtOpenCG%+mtNotOpenC
G%+resultrankG%&rank1G%&rank2GFit%+resulttempG%+gtbienluanG%'nghiemG%*valuepara
GF[y%)ruletempGF$F$C5>FKF[z>Fin-FfzFeal>F`o-F^zFeal>Fa[lF8>F7-%1ArgueRankByGaus
sG6&FKFinF`oF>>F][l&F7F\o>Fbdl&F7F]o>Fh^l&F7Fhel>F_]l-_F_z%-DeleteColumnG6$Fh^l
F`o>F[]l-F^fo6&F_]lFinFi^lF>>F[[l-%(GetRankG6#&F][lF\o>F_[l-F`go6#&&F[]lF\oF\o@
$3/-Fdo6#F][lF?/-FdoFagoF?@'0F[[lF_[lC&>FjalFH>Fc[l7&Fh^l/-%%uitRG6#%%OpenGF[[l
/FghoF_[lFjal>Fbdl7$-Ffn6#FbdlFc[lO6%FHFHFbdl/F[[lFi^lC&>Fjal&-%2MethodGaussJor
danG6$Fh^lFiglF]o>Fc[lFdho>FbdlF\ioO6%F?FjalFbdlC&>FjalFdio>Fc[lFdho>FbdlF\ioO6
%FVFjalFbdl>F\al&&FafoF\o6#;F?,&-Fdo6#FdjoF?FVF?@%F`hoC%>Fc\l7$FH-Ffn6#F\al>Fa[
l7$FahmFc\l>FjalFHC%>FjalFdio@%Faio>Fc\l7%F?F^[pFjal>Fc\l7%FVF^[pFjal>Fa[lFa[p>
Fc[l7'F^[pFh^lFehoFjhoFjal>FbdlF\io?(F<F^oF?F[hoFAC)@%/-F]ao6#&&F][lFioF]oFHC&>
Fe[l-Fc`o6#Fe\p>Ff]l-Fj`m6$/F>Fe[lFK>Ff]l-Fhhn6#Ff]l>Fiz-Fhfo6$Ff]lF`oC)>Ff]l-F
ftFcfl>Fiz-FftF[\n>Fe[lFh\p>Ff]l-Fj`m6$F]]pFf]l>Ff]lF_]p>Fiz-Fj`m6$F]]pFiz>Fiz-
Fhhn6#Fiz>F[[l-FgflF`]p>F_[l-FgflFc^p>F\al&Fe\pF\o@%F`hoC%>Fc\l7$FHF\al>Fa[lFa[
p>FjalFHC%>Fjal&-Ffio6$Ff]lFiglF]o@%Faio>Fc\l7%F?F\alFjal>Fc\l7%FVF\alFjal>Fa[l
Fa[p>Fc[l7'F\alFf]lFehoFjhoFjal>FbdlF\io@%/FGFiilO6$Fa[lFbdl?(F<F?F?-FdoFbhmFA@
'/&&Fa[lFioF\oF?C$-Fcel6#QM|+H&#7879;~c|^z~nghi&#7879;m~duy~nh&#7845;t~khiF$@%2
Fiel-Fdo6#Fg`p-F`y6$Q$KhiF$&Fg`p6#;F^oFc`pC%-F`y6$Fbap&Fg`pF]o-Fcel6#Q(Nghiem:F
$-F`y6#&Fg`p6#F^ap/Ff`pFVC&-Fcel6#QG|+H&#7879;~v|_z~s&#7889;~nghi&#7879;m~khiF$
@%F]apF`apFgapFjapF]bpC$-Fcel6#Q?|+H&#7879;~v|_z~nghi&#7879;m~khi~F$@%F]apF`apF
gapF$F$F$6#FielF^fot+6&F[`mFbqFcqFi`o6+F/Fiw%(mtstairGFet%-lelestandardG%*nstan
dardG%2resultStairMatrixGF[yFitF$F$C+>FinF[z>F[]l-%3StairMatrixByGaussG6$FinFG>
FKFggo>Fh^l&F[]lF]o>F`o&F[]lFhel>F7&F[]lF[fl@$2F7F>?(F<FgjnF?F>FA?(F:F?F?FGFA@$
/-F]rF`doF?>F`o7$-FfnF]jmFado>F_]l-%5ArgueRankStairMatrixG6%FKF`oF@O6%F_]lFh^lF
KF$F$F$6#F`pF\_mt+6#%%exprG6$'%"FGF_`m%&expr1GF$F$Z%@)5-Fcu6$FE%)constantG-Fcu6
$FE%'stringGO<"5-Fcu6$FE%%nameG-Fcu6$FE%(indexedGO<#FE5-Fcu6$FEFchl-Fcu6$FEF_`m
C%>F<Fcfp?&F:FEFA>F<-%&unionG6$F<-F\_mFgnOF<O-F\_m6#<#-FfnF\vF$OFf_mF$F$F$6#F?F
`got+Fe`o6$%$lenGFdinF$F$C%>F<-FdoF\v@%0&FEFio%4NotUsingStairMatrixG>F:-F]ao6#F
jhp>F:-F]ao6#&FE6#,&F<F?FVF?OF:F$F$F$6#F?Faent+6#'Fbeo&Fe_l6#Fbam6)F/%)alphabet
G%(lnghiemG%%varsG%)lreplaceG%-resultnghiemG%*stringVarGF$F$C)>F:7<%#_aG%#_bG%#
_cG%#_dG%#_eG%#_fG%#_gG%#_hG%#_iG%#_jG%#_kG%#_lG%#_mG%#_nG%#_oG%#_pG%#_qG%#_rG%
#_sG%#_tG%#_uG%#_vG%#_wG%#_xG%#_yG%#_zG>FK-F`[mF_gp>Fin-F\_mFeal>F`oF8?(F<F?F?-
FdoFh_lFAC$>F[]l-F`[m6$&FinFioFafp@$/FggoQ"_F$>F`o7$Fjdp/F[]qFho>F7-Fj`m6$F`oFE
OF7F$F$F$6#F?%/uitLinearSolveGt+6&'%&inputGFchlFgt>FcglFfgl>FhglFigl6*F/%(setva
rsG%$numGFcqFi`o%)variableGF^gmFitF$F$Z%C)>FKFghp>F:-F\_mF^ao>F:<#&Fen6#;F?,&Fc
oF?!"(F?>Fin-F^zF^ao-Fcel6#Q7|*L&#7901;i~gi&#7843;i|+F$@)/FKF?C$-Fcel6#QTH&#787
9;~ph|hz|`zng~tr&igrave;nh~kh|_zng~c|^z~tham~s&#7889;F$@%FarC%-Fcel6#QLTr|hz&#7
901;ng~h&#7907;p~kh|_zng~c|^z~bi&#7871;n|+F$>F[]lF_ao>Fh^l-F_gl6%F[]l/-F`[m6$Q'
methodF$FeglFG/F_[mF@C'@$0FcoF^\lYQHInvalid~Syntax:~input~value~is~invalid~F$-F
cel6#Q8Truong~hop~c|^z~ten~bien|+F$>F[]lF_ao>F[]l-Fh_m6$F[]lF:>Fh^lF``q/FKF^oC%
-Fcel6#Q;He~ph|hz|`zng~trinh~co~tham~soF$>F`o<#&FEF]o@%/-%*intersectG6$F:F`oF`o
C$>F[]lF_ao>Fh^l-Fbao6&F[]lF[bqFb`qFf`qYQMInvalid~Syntax:~Parameter~is~not~vali
d~valueF$/FKFielC&Ffaq>F`oFjaq>F7&FEFhel@%/FcoFin@%F]bq@%/-F_bq6$F:F7F7C%>F[]lF
_ao>F[]l-Fh_mFd]l>Fh^lFdbqYQLInvalid~Syntax:~Set~of~variable~are~invalidF$YQEIn
valid~Syntax:~Parameter~is~invalidF$YQ.Invalid~InputF$YF^dqOFh^lF$OFf_mF$F$F$6#
F^oFhrt+F^inFainF$F$C(>FKF8?&F<F>FAC(>FinF8>F`oF]jn>F7FH?(F:FGF?F@FA@%0FejnFH>F
7FgjnFedl>FinFijn>FKF[[o>F[]lF][o>Fh^lF`[o?(F<F^oF?FgdlFA@$Fc[oC$>F[]lFd[o>Fh^l
Fi[oOFh^lF$F$F$6#F`pF$
